---
name: JSON Schema
permissions: {}
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/json-schema.yaml
      - registry.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/json-schema.yaml
      - registry.yaml
jobs:
  json-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: aquaproj/registry-action/validate-json-schema@39773065a44549758440b90a9e25f713c7e1db34 # tag=v0.1.4
