name: renovate-config-validator

permissions: {}
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config-validator.yaml
      - renovate.json5

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@7ab3d8f19305664925f3e626580f075f14e40386 # tag=v0.1.2
